export const ALLERGENS = new Set([
  'Kuhmilch','Weizen','Schalentiere','Ei','Soja','Sesam','Fisch',
  'Cashew/Pistazie','Mandel','Walnuss/Pekannuss','Haselnuss','Erdnuss',
  'Lachs','Kabeljau','Krabbe','Hummer','Garnele','Forelle','Sardine',
  'Eiernudeln','Haferflocken','Nudeln','Brot','Edamame','Tofu','Tahini'
]);

export const CATEGORIES = [
  'Gemüse','Obst','Fleisch','Meeresfrüchte',
  'Hülsenfrüchte','Getreide','Milchprodukte','Nüsse & Samen'
];

// phase: frühester empfohlener Einführungsmonat
export const FOODS = {
  'Gemüse': [
    { name:'Karotte', phase:6, prep:'Weich garen und pürieren, oder in fingerförmige Stifte (ca. 7–8 cm) schneiden. Roh erst ab ~12 Monaten.', tips:'Gut verträglich, süßlicher Geschmack – ideal als Erstgemüse. Kann Stuhl orange färben – harmlos.' },
    { name:'Süßkartoffel', phase:6, prep:'Backen oder dämpfen, dann pürieren oder in weiche Stücke schneiden.', tips:'Sehr gut verträglich, nährstoffreich. Gute Quelle für Beta-Carotin und Ballaststoffe.' },
    { name:'Butternutkürbis', phase:6, prep:'Im Ofen weich backen, pürieren oder löffelgerecht zerdrücken.', tips:'Sehr weich und süßlich – gut als erstes Gemüse geeignet.' },
    { name:'Eichelkürbis', phase:6, prep:'Backen bis butterweich, Fruchtfleisch auslöffeln und pürieren.', tips:'Wie Butternutkürbis gut verträglich. Kerne vor dem Backen entfernen.' },
    { name:'Kürbis', phase:6, prep:'Backen oder dämpfen bis weich, pürieren oder in weiche Würfel schneiden.', tips:'Mild und gut verträglich. Hokkaido eignet sich besonders gut (Schale essbar).' },
    { name:'Zucchini', phase:6, prep:'Dämpfen oder braten bis weich, pürieren oder in Stücke schneiden.', tips:'Mild und gut verträglich. Enthält viel Wasser – gut hydratisierend.' },
    { name:'Brokkoli', phase:6, prep:'Röschen dämpfen bis weich (ca. 8–10 Min). Als Püree oder ganzer Röschen zum Greifen.', tips:'Kann Blähungen verursachen – kleine Mengen starten. Enthält Eisen und Vitamin C.' },
    { name:'Blumenkohl', phase:6, prep:'Dämpfen bis weich, pürieren oder Röschen zum Greifen anbieten.', tips:'Kann wie Brokkoli Blähungen verursachen. Milder im Geschmack als Brokkoli.' },
    { name:'Spinat', phase:6, prep:'Kurz blanchieren, gut abtropfen und pürieren. Nie wieder erhitzen!', tips:'⚠ Nitratreich – frisch zubereiten und NICHT aufwärmen (Nitrit-Bildung). Max. 1–2x pro Woche unter 12 Monaten.' },
    { name:'Grünkohl', phase:6, prep:'Stiele entfernen, Blätter weich dämpfen und pürieren.', tips:'Sehr nährstoffreich (Eisen, Kalzium). Kräftiger Geschmack – gut mit milderem Gemüse mischen.' },
    { name:'Collard-Grünkohl', phase:6, prep:'Stiele entfernen, lange dämpfen bis sehr weich, pürieren.', tips:'Wie Grünkohl – reich an Kalzium und Eisen.' },
    { name:'Mangold', phase:6, prep:'Stiele und Blätter trennen, weich garen (Stiele dauern länger). Pürieren.', tips:'⚠ Nitratreich wie Spinat – nicht aufwärmen, max. 2x pro Woche.' },
    { name:'Kartoffel', phase:6, prep:'Weich kochen, stampfen oder pürieren. Kein Salz zugeben.', tips:'Gut verträglich und sättigend. Grüne Stellen und Keime entfernen (Solanin).' },
    { name:'Pastinake', phase:6, prep:'Schälen, weich garen, pürieren oder als Sticks zum Greifen.', tips:'Süßlicher, nussiger Geschmack – meist sehr beliebt. Nährstoffreich.' },
    { name:'Grüne Bohne', phase:6, prep:'Weich garen, pürieren oder in kurze Stücke schneiden.', tips:'Gut verträglich. Roh nie anbieten – enthält unverdauliche Lektine.' },
    { name:'Paprika', phase:6, prep:'Immer weich garen oder rösten – roh ist Erstickungsgefahr und schwer verdaulich. In Streifen oder püriert.', tips:'Reich an Vitamin C. Rote Paprika ist süßer und besser verträglich als grüne.' },
    { name:'Rote Bete', phase:6, prep:'Weich garen und pürieren oder in Stücke schneiden.', tips:'Kann Stuhl und Urin rot/rosa färben – harmlos, kann aber erschrecken! Nitratreich wie Spinat.' },
    { name:'Spaghettikürbis', phase:8, prep:'Backen, mit Gabel zu Fäden ziehen – natürliche "Nudeln" für Babys.', tips:'Interessante Textur zum Selbstessen. Gut ab ca. 8 Monaten wenn Greifkompetenz vorhanden.' },
    { name:'Aubergine', phase:8, prep:'Immer garen – roh ungenießbar. Braten oder backen, Fleisch aus der Schale lösen.', tips:'⚠ Roh leicht giftig (Solanin). Gut gegarte Aubergine ist weich und verträglich.' },
    { name:'Mais', phase:8, prep:'Körner pürieren oder als weiche Polenta anbieten. Ganze Körner sind Erstickungsgefahr.', tips:'⚠ Ganze Maiskörner sind Erstickungsgefahr bis ~4 Jahre! Immer pürieren oder als Polenta.' },
    { name:'Gurke', phase:8, prep:'Schälen, entkernen, in Sticks schneiden. Gut gekühlter Stick hilft auch beim Zahnen.', tips:'Zu ~96 % Wasser – kein großer Nährwert, aber gut zum Erkunden von Texturen.' },
    { name:'Rosenkohl', phase:8, prep:'Sehr weich dämpfen oder kochen, halbieren oder pürieren.', tips:'Starke Blähungsgefahr – nur in kleinen Mengen. Reich an Vitamin K und C.' },
    { name:'Weißkohl', phase:8, prep:'Sehr weich garen, fein pürieren. In kleinen Mengen einführen.', tips:'Kann erhebliche Blähungen verursachen. Gut in kleinen Mengen mit anderen Gemüsesorten mischen.' },
    { name:'Champignon', phase:8, prep:'Immer gut durchgaren – nie roh anbieten. In kleine Stücke schneiden.', tips:'Roh nicht empfohlen (schwer verdaulich). Gut gegart weich und verträglich.' },
    { name:'Zwiebel', phase:8, prep:'Immer garen – roh ungeeignet. Als Würzzutat in Gemüsepürees oder Fleischgerichten.', tips:'Roh ungeeignet. Weich gegart gut verträglich und geschmacksgebend.' },
    { name:'Knoblauch', phase:8, prep:'Sparsam als Würzzutat verwenden, immer garen.', tips:'Intensiver Geschmack – kleine Mengen ausreichend. Kann Blähungen verursachen.' },
    { name:'Spargel', phase:8, prep:'Holzige Enden entfernen, weich dämpfen. Ganze Stangen zum Greifen oder püriert.', tips:'Kann Urin eigentümlich riechen lassen – harmlos. Weißer Spargel milder im Geschmack.' },
    { name:'Romanesco', phase:8, prep:'Wie Blumenkohl – Röschen dämpfen bis weich, pürieren oder zum Greifen.', tips:'Ähnliche Eigenschaften wie Blumenkohl. Spannende Optik.' },
    { name:'Pumpkin (Hokkaido)', phase:6, prep:'Mit Schale backen bis weich, pürieren. Schale wird bei Hokkaido mit gegessen.', tips:'Hokkaido-Schale ist nach dem Backen weich und essbar. Sehr gut verträglich.' },
    { name:'Ingwer', phase:10, prep:'Nur als kleine Menge Würzzutat, frisch gerieben oder als Pulver.', tips:'Sehr intensiv – nur Spuren verwenden. Kann Magen reizen bei größeren Mengen.' },
  ],
  'Obst': [
    { name:'Banane', phase:6, prep:'Reife Banane zerdrücken oder in Stücke schneiden. Kein Garen nötig.', tips:'Sehr praktisch und nährstoffreich. Überreife Bananen sind am weichsten. Kann Verstopfung verursachen.' },
    { name:'Avocado', phase:6, prep:'Reife Avocado zerdrücken oder in Spalten schneiden. Kein Garen nötig.', tips:'Ausgezeichnete Quelle für gesunde Fette – wichtig für Gehirnentwicklung. Dunkel gewordenes Fruchtfleisch ist harmlos.' },
    { name:'Birne', phase:6, prep:'Reife Birne pürieren oder in weiche Stücke schneiden. Sehr reife Birnen müssen nicht gegart werden.', tips:'Sehr reife Birnen sind weich genug roh. Kann bei Übermaß Durchfall verursachen (Sorbit).' },
    { name:'Apfel', phase:6, prep:'Weich dämpfen und pürieren oder als Apfelmus. Roh erst ab ~10 Mo fein gerieben.', tips:'⚠ Roh und hart ist Erstickungsgefahr! Immer weich garen oder fein reiben bis mind. 10 Monate.' },
    { name:'Pfirsich', phase:6, prep:'Schälen, pürieren oder in sehr weiche Stücke schneiden. Stein entfernen!', tips:'Stein immer entfernen! Kann allergische Reaktionen auslösen (Rosengewächs-Frucht).' },
    { name:'Aprikose', phase:6, prep:'Schälen, Kern entfernen, pürieren oder in weiche Stücke.', tips:'Kern immer entfernen. Reich an Beta-Carotin.' },
    { name:'Pflaume', phase:6, prep:'Kern entfernen, pürieren oder in weiche Stücke schneiden.', tips:'Natürliches Abführmittel – gut bei Verstopfung. Kern unbedingt entfernen.' },
    { name:'Backpflaume', phase:6, prep:'Einweichen, Kern entfernen, pürieren.', tips:'Konzentriertes Abführmittel – sparsam verwenden. Gut bei Verstopfung in kleinen Mengen.' },
    { name:'Mango', phase:6, prep:'Reife Mango pürieren oder in kleine weiche Stücke schneiden.', tips:'Sehr nährstoffreich (Vitamin A, C). Auf Reife achten – unreife Mango ist hart und säuerlich.' },
    { name:'Heidelbeere', phase:6, prep:'Immer zerdrücken oder halbieren – ganze Beeren sind Erstickungsgefahr bis ~12 Mo.', tips:'⚠ Ganze runde Beeren sind Erstickungsgefahr! Immer zerdrücken. Reich an Antioxidantien.' },
    { name:'Erdbeere', phase:6, prep:'Pürieren oder in kleine Stücke schneiden. Grüne Blätter entfernen.', tips:'Kann Hautreaktionen verursachen (Pseudoallergie). In kleinen Mengen einführen und beobachten.' },
    { name:'Himbeere', phase:6, prep:'Zerdrücken oder pürieren – Kerne können abgesiebt werden.', tips:'Kerne können störend sein. Reich an Ballaststoffen und Vitamin C.' },
    { name:'Brombeere', phase:6, prep:'Zerdrücken oder pürieren – Kerne können abgesiebt werden.', tips:'Wie Himbeere. Reich an Vitamin C und Antioxidantien.' },
    { name:'Wassermelone', phase:6, prep:'Kerne entfernen, in kleine weiche Stücke schneiden oder pürieren.', tips:'Zu ~92 % Wasser – gut hydratisierend. Alle Kerne sorgfältig entfernen.' },
    { name:'Cantaloupe-Melone', phase:6, prep:'Kerne entfernen, in weiche Stücke schneiden.', tips:'Weich und süß – meist gut angenommen. Kerne entfernen.' },
    { name:'Honigmelone', phase:6, prep:'Kerne entfernen, in weiche Stücke schneiden oder pürieren.', tips:'Mild und gut verträglich. Kerne immer entfernen.' },
    { name:'Kokosnuss', phase:8, prep:'Kokosmilch (ungesüßt) als Zutat in Speisen. Kokosraspeln erst ab 12 Mo (Erstickungsgefahr).', tips:'Kokosmilch in Currys oder Brei gut verwendbar. Kokosraspeln erst ab 12 Mo wegen Erstickungsgefahr.' },
    { name:'Kirsche', phase:8, prep:'Kerne und Stiele sorgfältig entfernen! Pürieren oder in sehr kleine Stücke.', tips:'⚠ Kern ist hochgefährlich – sehr sorgfältig entkernen! Am besten pürieren.' },
    { name:'Weintraube', phase:8, prep:'IMMER längs halbieren oder vierteln – ganze Trauben sind gefährlich!', tips:'⚠ Ganze Trauben gehören zu den häufigsten Erstickungsursachen bei Kindern! Immer längs halbieren, bis mind. 5 Jahre.' },
    { name:'Ananas', phase:8, prep:'Schälen, Strunk entfernen, in kleine weiche Stücke. Kurz erwärmen macht sie weicher.', tips:'Enthält Bromelain – kann Mundschleimhaut reizen. In kleinen Mengen einführen.' },
    { name:'Kiwi', phase:8, prep:'Schälen, in kleine Stücke schneiden.', tips:'Häufiges Allergen! Langsam einführen und beobachten. Kann Mundreizungen verursachen. Reich an Vitamin C.' },
    { name:'Tomate', phase:8, prep:'Schälen, entkernen, weich garen. Roh erst ab ~10 Mo in kleinen Stücken.', tips:'Kann Windeldermatitis verursachen (Säure). In kleinen Mengen einführen.' },
    { name:'Drachenfrucht', phase:8, prep:'Fruchtfleisch löffeln oder in Stücke schneiden, Samen sind harmlos.', tips:'Mild im Geschmack. Rote Sorte kann Stuhl und Urin rosa färben – harmlos.' },
    { name:'Kochbanane', phase:8, prep:'Immer kochen oder backen – roh nicht verdaulich. Pürieren oder in Stücke.', tips:'Roh ungeeignet (stärkereich und hart). Gegart gut verträglich und sättigend.' },
    { name:'Orange', phase:8, prep:'Filets ohne Häutchen anbieten, oder Saft in kleinen Mengen (max. 30–60 ml/Tag).', tips:'Säuerlich – kann Windeldermatitis verursachen. Erst ab 8 Monaten und in kleinen Mengen.' },
    { name:'Preiselbeere', phase:10, prep:'Immer kochen und pürieren – roh sehr sauer und hart.', tips:'Meist nur als gekochte Sauce. Sehr sauer – mit Obst kombinieren das natürlich süßt.' },
    { name:'Grapefruit', phase:10, prep:'Filets ohne Häutchen, in kleinen Mengen.', tips:'Sehr sauer – zurückhaltend einführen.' },
    { name:'Zitrone', phase:10, prep:'Nur als Würzzutat (Saft) in kleinen Mengen.', tips:'Zu sauer für größere Mengen. Als Spritzer zur Verfärbungsverhinderung bei Apfel/Avocado okay.' },
    { name:'Limette', phase:10, prep:'Nur als Würzzutat in kleinen Mengen.', tips:'Wie Zitrone – zu sauer für direkte Verwendung in größeren Mengen.' },
  ],
  'Fleisch': [
    { name:'Hähnchen', phase:6, prep:'Sehr weich garen (kochen/dämpfen), pürieren oder in Fasern zerteilen. Kein Salz.', tips:'Gutes erstes Fleisch – mild und gut verdaulich. Wichtige Eisenquelle. Haut entfernen.' },
    { name:'Pute', phase:6, prep:'Wie Hähnchen – weich garen, pürieren oder zerfasern.', tips:'Mager und gut verträglich. Gute Alternative zu Hähnchen.' },
    { name:'Rind', phase:6, prep:'Sehr weich schmoren oder kochen, pürieren oder fein zerfasern.', tips:'Beste Eisenquelle unter den Fleischsorten – wichtig für Babyentwicklung. Magere Stücke bevorzugen.' },
    { name:'Hackfleisch (Rind)', phase:6, prep:'Vollständig durchgaren, pürieren oder als kleine weiche Bällchen formen.', tips:'Immer gut durchgaren (Kerntemperatur mind. 75°C). Reich an Eisen und Zink.' },
    { name:'Hühnerleber', phase:6, prep:'Vollständig durchgaren, pürieren. Nur 1x pro Woche maximal.', tips:'Extrem eisenreich – aber max. 1x pro Woche wegen Vitamin A (Überdosis möglich bei mehr). Gut durchgaren.' },
    { name:'Ei', phase:6, prep:'Vollständig hart kochen (mind. 10 Min.) oder als Rührei vollständig durchgaren. Nie roh!', tips:'Frühzeitige Einführung (ab 6 Mo) reduziert Allergierisiko! Immer vollständig durchgaren. Häufiges Allergen – auf Reaktion achten.' },
    { name:'Lamm', phase:6, prep:'Sehr weich schmoren, pürieren oder zerfasern.', tips:'Aromatisch – viele Babys mögen den Geschmack. Reich an Eisen und Zink.' },
    { name:'Schwein', phase:8, prep:'Magere Stücke weich garen, pürieren oder zerfasern. Immer vollständig durchgaren.', tips:'Immer vollständig durchgaren. Fettarme Stücke bevorzugen. Keine Wurstwaren (zu viel Salz/Nitrate).' },
  ],
  'Meeresfrüchte': [
    { name:'Lachs', phase:6, prep:'Vollständig durchgaren (kein Sushi!), alle Gräten entfernen, pürieren oder in Flocken.', tips:'Reich an Omega-3 – wichtig für Gehirnentwicklung. Frühzeitige Einführung empfohlen. Gräten sorgfältig entfernen!' },
    { name:'Kabeljau', phase:6, prep:'Vollständig durchgaren, Gräten entfernen, zerflocken.', tips:'Magerer, milder Fisch – gut als erster Fisch. Frühzeitige Einführung reduziert Fischallergie-Risiko.' },
    { name:'Sardine', phase:6, prep:'Aus der Dose (in Wasser/Öl, nicht Salz), Gräten zerdrücken (sie sind weich), zerflocken.', tips:'Dosenware praktisch. Weiche Gräten sind essbar und liefern Kalzium. Niedrig in Quecksilber.' },
    { name:'Forelle', phase:6, prep:'Vollständig durchgaren, Gräten sehr sorgfältig entfernen.', tips:'Süßwasserfisch – niedrig in Quecksilber. Gräten besonders sorgfältig entfernen.' },
    { name:'Garnele', phase:8, prep:'Vollständig durchgaren, in kleine Stücke schneiden oder pürieren.', tips:'Häufiges Allergen – langsam einführen. Immer vollständig durchgaren.' },
    { name:'Krabbe', phase:8, prep:'Vollständig durchgaren, fein zerteilen, auf Schalenreste prüfen.', tips:'Häufiges Allergen. Schalenreste sind Erstickungsgefahr – sehr sorgfältig prüfen.' },
    { name:'Hummer', phase:10, prep:'Vollständig durchgaren, Fleisch aus der Schale, fein zerteilen.', tips:'Häufiges Allergen. Schalenreste sorgfältig entfernen.' },
  ],
  'Hülsenfrüchte': [
    { name:'Linsen', phase:6, prep:'Rote Linsen weich kochen (kein Einweichen nötig), pürieren. Andere Sorten vorher einweichen.', tips:'Beste pflanzliche Eisenquelle! Mit Vitamin-C-reichen Lebensmitteln kombinieren (Paprika, Tomate) für bessere Eisenaufnahme.' },
    { name:'Kichererbsen', phase:6, prep:'Aus der Dose (abgespült) weich kochen oder zu Hummus pürieren. Ganze Kichererbsen bis 12 Mo zerdrücken.', tips:'Gut verträglich. Als Hummus (ohne zu viel Tahini und Zitrone anfangs) gut geeignet.' },
    { name:'Erbsen', phase:6, prep:'Tiefkühlerbsen kurz garen und pürieren oder zerdrücken. Nie ganz servieren.', tips:'⚠ Ganze Erbsen sind Erstickungsgefahr! Immer pürieren oder zerdrücken bis mind. 12 Monate.' },
    { name:'Edamame', phase:6, prep:'Schoten entfernen! Bohnen weich garen und pürieren oder zerdrücken.', tips:'⚠ Schoten niemals essen. Enthält Soja – häufiges Allergen, langsam einführen.' },
    { name:'Tofu', phase:6, prep:'Weichen Tofu zerdrücken oder in kleine Würfel schneiden. Fester Tofu in Stücke schneiden und braten.', tips:'Gute pflanzliche Proteinquelle. Enthält Soja – häufiges Allergen, langsam einführen.' },
    { name:'Erdnuss', phase:6, prep:'NUR als glattes Erdnussbutter (dünn auf Löffel oder in Brei). Niemals ganze Nüsse oder Stücke!', tips:'⚠ Frühzeitige Einführung (ab 6 Mo) reduziert nachweislich Allergierisiko! Ganze Erdnüsse erst ab 5 Jahren. Bei Ekzem oder Ei-Allergie: zuerst Kinderarzt fragen.' },
    { name:'Schwarze Bohnen', phase:8, prep:'Aus der Dose (abgespült) weich kochen, pürieren oder zerdrücken.', tips:'Gut für Eisen und Ballaststoffe. Ganze Bohnen bis 12 Mo zerdrücken.' },
    { name:'Kidneybohnen', phase:8, prep:'Aus der Dose (abgespült) oder vollständig selbst kochen. Pürieren oder zerdrücken.', tips:'⚠ Rohe oder halbgare Kidneybohnen sind giftig (Phasin)! Immer vollständig kochen. Dose ist sicherer.' },
    { name:'Cannellini-Bohnen', phase:8, prep:'Aus der Dose (abgespült), zerdrücken oder pürieren.', tips:'Milde weiße Bohnen – gut verträglich. Gut zerdrücken bis 12 Mo.' },
    { name:'Pintobohnen', phase:8, prep:'Aus der Dose (abgespült), zerdrücken oder pürieren.', tips:'Wie andere Bohnen – gut zerdrücken. Reich an Ballaststoffen und Eisen.' },
  ],
  'Getreide': [
    { name:'Haferflocken', phase:6, prep:'Zarte Haferflocken zu Brei kochen (nicht Knusper-/Granola-Varianten). Mit Muttermilch oder Wasser aufkochen.', tips:'Enthält Gluten – frühzeitige Einführung zwischen 4–12 Mo empfohlen für Zöliakie-Prävention. Sehr nährstoffreich.' },
    { name:'Basmatireis', phase:6, prep:'Weich kochen (mehr Wasser als normal), zerdrücken oder als Brei servieren.', tips:'Gut verträglich. Sehr weich kochen für Babys. Kein Salz.' },
    { name:'Quinoa', phase:6, prep:'Gut waschen (Saponine!), weich kochen. Für jüngere Babys pürieren.', tips:'Glutenfrei und eiweißreich. Vor dem Kochen immer gut waschen (bittere Saponine).' },
    { name:'Polenta', phase:6, prep:'Weich kochen zu cremiger Konsistenz. Kein Salz zugeben.', tips:'Glutenfrei und mild. Gut als erste Getreideeinführung.' },
    { name:'Nudeln', phase:8, prep:'Sehr weich kochen (al dente ist zu hart!), in kleine Stücke schneiden oder zerdrücken.', tips:'Enthält Gluten (Weizen). Sehr weich kochen – al dente ist für Babys zu zäh.' },
    { name:'Eiernudeln', phase:8, prep:'Sehr weich kochen, in kleine Stücke schneiden.', tips:'Enthält Gluten (Weizen) UND Ei – zwei häufige Allergene. Langsam einführen.' },
    { name:'Brot', phase:8, prep:'Weiches Weißbrot oder Toastbrot in kleinen Stücken. Rinde anfangs entfernen.', tips:'Enthält Gluten. Volles Brotstück kann sich im Mund zu einem Klumpen formen – Erstickungsgefahr. In kleinen Stücken.' },
  ],
  'Milchprodukte': [
    { name:'Joghurt', phase:6, prep:'Naturjoghurt (Vollmilch, ungesüßt). Kein Fruchtjoghurt mit Zuckerzusatz.', tips:'Kuhmilch als Getränk erst ab 12 Mo, ABER Joghurt und Käse als Beikost ab 6 Mo okay! Immer Vollmilch-Joghurt wählen.' },
    { name:'Ricotta', phase:6, prep:'Pur oder mit Obst/Gemüse mischen. Kein Salz.', tips:'Mild und cremig. Reich an Kalzium und Eiweiß.' },
    { name:'Mascarpone', phase:8, prep:'Sparsam als cremige Zutat, pur oder in Speisen gemischt.', tips:'Sehr fettreich – in kleinen Mengen. Mild im Geschmack.' },
    { name:'Mozzarella', phase:8, prep:'In sehr kleine Stücke reißen oder schneiden. Frischen (nicht gesalzenen) Mozzarella verwenden.', tips:'Zähe Konsistenz kann problematisch sein – wirklich sehr kleine Stücke. Frischer Mozzarella ohne Salz.' },
    { name:'Ziegenkäse', phase:8, prep:'Weichen Ziegenkäse pürieren oder zerdrücken. Salzgehalt beachten.', tips:'Salzgehalt prüfen – zu viel Salz ist für Babys schädlich. Weiche Sorten bevorzugen.' },
    { name:'Schweizer Käse', phase:10, prep:'Sehr fein reiben oder in winzige Stücke. Auf Salzgehalt achten.', tips:'Harte Konsistenz und Salzgehalt beachten. Fein gerieben als Zutat zu Gemüse.' },
    { name:'Kuhmilch', phase:12, prep:'Als Getränk erst ab 12 Monaten. Als Zutat (Joghurt, Käse, in Brei) ab 6 Mo okay.', tips:'⚠ Kuhmilch als Hauptgetränk erst ab 12 Monaten – davor verdrängt sie nährstoffreiche Muttermilch/Säuglingsnahrung. Als Zutat in Speisen ab 6 Mo okay.' },
  ],
  'Nüsse & Samen': [
    { name:'Erdnuss', phase:6, prep:'NUR als glattes Erdnussbutter (dünn auf Löffel oder in Brei einrühren). Niemals ganze Nüsse!', tips:'⚠ Frühzeitige Einführung empfohlen – Forschung zeigt klare Allergieprävention. Ganze Erdnüsse erst ab 5 Jahren! Bei Ekzem oder Ei-Allergie: zuerst Kinderarzt fragen.' },
    { name:'Tahini', phase:6, prep:'Als Zutat in Hummus oder verdünnt mit Wasser. In kleinen Mengen.', tips:'Enthält Sesam (Allergen). Langsam einführen und beobachten. Reich an Kalzium.' },
    { name:'Mandel', phase:6, prep:'NUR als glattes Mandelmus oder fein gemahlen in Brei. Niemals ganze oder gehackte Mandeln.', tips:'⚠ Ganze Mandeln/Nüsse sind Erstickungsgefahr bis mind. 5 Jahre. Nur als glattes Mus.' },
    { name:'Cashew/Pistazie', phase:6, prep:'NUR als glattes Cashewmus. Niemals ganze oder gehackte Nüsse.', tips:'⚠ Ganze Nüsse sind gefährlich bis 5 Jahre! Cashewmus ist mild und beliebt.' },
    { name:'Walnuss/Pekannuss', phase:6, prep:'NUR als Walnussmus oder sehr fein gemahlen in Brei.', tips:'⚠ Ganze Nüsse erst ab 5 Jahren. Reich an Omega-3-Fettsäuren.' },
    { name:'Haselnuss', phase:6, prep:'NUR als glattes Haselnussmus (zuckerfreies Nussmus, nicht Nutella!).', tips:'⚠ Ganze Nüsse erst ab 5 Jahren. Kein Nutella (zu viel Zucker/Salz). Reines Haselnussmus verwenden.' },
    { name:'Chiasamen', phase:8, prep:'In Flüssigkeit mind. 10 Min. quellen lassen bis Gel entsteht, dann in Brei oder Joghurt.', tips:'⚠ Trockene Chiasamen können sich in der Speiseröhre aufquellen! Immer erst in Flüssigkeit quellen lassen.' },
  ],
};
